variable "prefix" {
  description = "Specifies the prefix added to the names of all resources. Default is 'gcp-suse-ai-tf'."
  type        = string
  default     = "gcp-suse-ai-tf"
}

variable "region" {
  description = "Specifies the Google region used for all resources. Default is 'us-west2'."
  type        = string
  default     = "us-west2"
  validation {
    condition = contains([
      "asia-east1",
      "asia-east2",
      "asia-northeast1",
      "asia-northeast2",
      "asia-northeast3",
      "asia-south1",
      "asia-south2",
      "asia-southeast1",
      "asia-southeast2",
      "australia-southeast1",
      "australia-southeast2",
      "europe-central2",
      "europe-north1",
      "europe-southwest1",
      "europe-west1",
      "europe-west10",
      "europe-west12",
      "europe-west2",
      "europe-west3",
      "europe-west4",
      "europe-west6",
      "europe-west8",
      "europe-west9",
      "me-central1",
      "me-central2",
      "me-west1",
      "northamerica-northeast1",
      "northamerica-northeast2",
      "southamerica-east1",
      "southamerica-west1",
      "us-central1",
      "us-east1",
      "us-east4",
      "us-east5",
      "us-south1",
      "us-west1",
      "us-west2",
      "us-west3",
      "us-west4"
    ], var.region)
    error_message = "Invalid Region specified."
  }
}

variable "create_ssh_key_pair" {
  description = "Specifies whether a new SSH key pair needs to be created for the instances. Default is 'true'."
  type        = bool
  default     = true
}

variable "ssh_private_key_path" {
  description = "Specifies the full path where the pre-generated SSH PRIVATE key is located (not generated by Terraform). Default is 'null'."
  type        = string
  default     = null
}

variable "ssh_public_key_path" {
  description = "Specifies the full path where the pre-generated SSH PUBLIC key is located (not generated by Terraform). Default is 'null'."
  type        = string
  default     = null
}

variable "ssh_username" {
  description = "The default SSH user for instance"
  type        = string
  default     = "opensuse" # Default for openSUSE/Amazon Linux on GCP
}

variable "ip_cidr_range" {
  description = "Specifies the range of private IPs available for the Google Subnet. Default is '10.10.0.0/24'."
  type        = string
  default     = "10.10.0.0/24"
}

variable "create_vpc" {
  description = "Specifies whether a VPC and Subnet should be created for the instances. Default is 'true'."
  type        = bool
  default     = true
}

variable "vpc" {
  description = "Specifies the Google VPC used for all resources. Default is 'null'."
  type        = string
  default     = null
}

variable "subnet" {
  description = "Specifies the Google Subnet used for all resources. Default is 'null'."
  type        = string
  default     = null
}

variable "create_firewall" {
  description = "Specifies whether a Google Firewall should be created for all resources. Default is 'true'."
  type        = bool
  default     = true
}

variable "spot_instance" {
  description = "Specifies whether the instances should be Spot (preemptible) VMs. Default is 'true'."
  type        = bool
  default     = true
}

variable "os_disk_type" {
  description = "Specifies the type of the disk attached to each node (e.g., 'pd-standard', 'pd-ssd', or 'pd-balanced'). Default is 'pd-ssd'."
  type        = string
  default     = "pd-ssd"
}

variable "os_disk_size" {
  description = "Specifies the size of the disk attached to each node, in GB. Default is '50'."
  type        = number
  default     = 50
}

variable "instance_type" {
  description = "Specifies the name of a Google Compute Engine machine type. Default is 'n2-standard-16'."
  type        = string
  default     = "n1-standard-16"
}

variable "data_disk_count" {
  description = "Specifies the number of additional data disks to attach to each VM instance. Default is 1."
  type        = number
  default     = 1
}

variable "data_disk_type" {
  description = "Specifies the type of the disks attached to each node (e.g., 'pd-standard', 'pd-ssd', or 'pd-balanced'). Default is 'pd-ssd'."
  type        = string
  default     = "pd-ssd"
}

variable "data_disk_size" {
  description = "Specifies the size of the additional data disks for each VM instance, in GB. Default is '350'."
  type        = number
  default     = 350
}

variable "startup_script" {
  description = "Specifies a custom startup script to run when the VMs start. Default is 'null'."
  type        = string
  default     = null
}

variable "gpu_type" {
  description = "Specifies the type of GPU to be used."
  default     = "nvidia-tesla-t4"
}

variable "gpu_count" {
  description = "Specifies the count of GPU to be attached to the VM."
  default     = 1
}

variable "project_id" {
  description = "Specifies the project ID for your Google cloud account."
  type        = string
  default     = null
}

variable "zone" {
  description = "Specifies the availability zone for resources."
  type        = string
  default     = "us-west2-b"
}

variable "rke2_version" {
  description = "The version of RKE2 to install"
  type        = string
  default     = "null"
}

variable "certified_os_image" {
  description = "Specifies whether to use the SUSE AI TF OS image released in the GitHub repository. If set to false, the default OpenSUSE image provided by the cloud provider will be used. Default is 'false'."
  type        = bool
  default     = false
}

variable "certified_os_image_tag" {
  description = "Specifies which GitHub release to use for the OpenSUSE image. Default is 'build-11'."
  type        = string
  default     = "build-11"
  validation {
    condition     = can(regex("^build-[0-9]+$", var.certified_os_image_tag))
    error_message = "Invalid value for certified_os_image_tag. Allowed values must match the format 'build-<number>'."
  }
}

variable "public_ip_source_addresses" {
  description = "List of CIDRs allowed to reach port 22 (SSH). Defaults to the public IP of the machine running Terraform."
  type        = list(string)
  default     = []
}
