name: Test Azure VM deploy and destroy

on:
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read

env:
  TF_VERSION: "1.10.5"
  TF_WORKING_DIR: tests/azure/infra-only
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  azure_vm_terraform_deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v3
        with:
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
      
      - name: Get GitHub Runner Public IP
        id: get_ip
        run: |
          # Fetch the public IP of the runner
          RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "RUNNER_IP=$RUNNER_IP" >> $GITHUB_ENV
          echo "Detected Runner IP: $RUNNER_IP"

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Apply
        run: terraform apply -var "subscription_id=$AZURE_SUBSCRIPTION_ID" -var "public_ip_source_addresses=[\"$RUNNER_IP/32\"]"  -auto-approve

      - name: Get public IP
        run: |
          ip=$(terraform output -json instance_public_ip | jq -r '.')
          echo "INSTANCE_IP=$ip" >> $GITHUB_ENV

      - name: Wait for SSH
        run: |
          echo "Checking $INSTANCE_IP..."
          for i in {1..30}; do
            nc -zv $INSTANCE_IP 22 && exit 0
            sleep 10
          done
          exit 1
        env:
          INSTANCE_IP: ${{ env.INSTANCE_IP }}

      - name: Terraform Destroy
        if: always()
        run: terraform destroy -var "subscription_id=$AZURE_SUBSCRIPTION_ID" -var "public_ip_source_addresses=[\"$RUNNER_IP/32\"]" -auto-approve
